- name: set owner and permissions on sites/default
  file:
    path: /var/www/html/drupal/web/sites/default/files
    owner: www-data
    group: www-data
    mode: 0775
    state: directory
- name: create directory for drupal logs
  file:
    path: /var/log/islandora/drupal
    owner: ubuntu
    group: ubuntu
    mode: 0775
    state: directory